version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          - v2-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}   
      - run: npm run build
      - run: npm run test
      - run: npm run coverage
      - run: npm run codecov
      - store_artifacts:
          path: ./coverage/clover.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: ./coverage
      - persist_to_workspace:
          root: .
          paths: .
  deployment:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run: sudo npm install -g --unsafe-perm now
      - deploy:
          name: Deploy & Alias
          command: now -t ${NOW_TOKEN} && now alias -t ${NOW_TOKEN} teletext-beta
workflows:
  version: 2
  test_build_deploy:
    jobs:
      - build
      - deployment:
          requires:
            - build
          filters:
            branches:
              only:
                - master